### ISSUE TITLE
Add option to disable decoding escaped characters in strings

### ISSUE THREAD

**Issue by absrd** [ruby/json#383]
I've come across JSON objects with serialized JSON objects with escaped unicode characters as values that have been used to create cryptographic signatures, e.g:
```
{
  "key": "{\"key\":\"\u003d\"}"
}
```
Verifying the signature requires the string to be untouched, but parsing it with the json gem decodes the code points.

**Comment by byroot** [comment]
I understand the ask, but this is way too niche of an option to justify the added complexity in my opinion.

**Comment by timvahlbrock** [comment]
I'm having a similar problem with the pact broker client, that uses this library. The main problem is, that some unicode characters may break the parsing when this module tries to parse them. The unicode character code for a surrogate `\uDAA5`, for example will cause "incomplete surrogate pair" to be thrown. Something that doesn't happen with an actual surrogate. I have also seen some unicode sequences causing problems when converting to json, although I'm not 100% sure that this is caused by this library (in the other case this module is explicitly visible in the call stack).

**Comment by timvahlbrock** [comment]
Seems like I got a bit of understanding of unicode surrogates wrong. I will investigate again and come back here if needed.
