### ISSUE TITLE
Transfer request for `ruby/json`

### ISSUE THREAD

**Issue by hsbt** [ruby/json#591]
Hi, @flori. 

I would like to transfer flori/json to ruby/json. Because I have following concerns:

* I can't update configuration of CI or toolchains.
* I can't add write grant for JRuby and TruffleRuby maintainers.
* Rails maintainer have some concerns for JSON gem like https://bugs.ruby-lang.org/issues/19528.

It's good time to move json repo under the ruby org.

I keep you as admin grant after transferring ruby org. How about transferring json repo to ruby org?

I already sent same request by email. But I didn't get your response yet. I'm happy to consider for that.

Thanks!

**Comment by rubyFeedback** [comment]
This actually also taps into ownership. I myself no longer use rubygems as a gem-author (I still use gems as a user, of course) after the somewhat recent 100.000 downloads restriction taking away control of what I can do with my own self-written gems on rubygems.org (other than profile deletion, of course, which I did to show that the 100.000 download limitation is totally arbitrary, with rubygems.org devs not even having the decency to indicate that gem-authors no longer have any control over gems they uploaded past the 100.000 threshold, yet still attributing the name of the gem author to code he/she can no longer change. (You can upload a new gem, of course, but the 100.000 download one is still attributed to your profile, and you are then forbidden to remove the old code, without rubygems.org forking the code at all whatsoever.)

What I have said at the same time, though, is that ruby needs some kind of control-system IN ADDITION to its flexibility. So, for instance, a way to indicate that "json" is under control of, say, ruby-core-team.

I am not saying that the namespace, say "module Json", becomes unchangable, mind you. That is a useful feature of ruby.

What I am saying, however had, is that there should be a place and a way to attribute "namespaces" and "ownership" somehow. This includes abandoned repositories, but also things that could be changed at run-time (and if you want to, you could always disallow a change when it is owned by ruby-core, for instance, although I would probably still keep it open for change).

With a flexible ownership model in place we can also have the same-named gem hosted on rubygems (with "gem install NAME" still referring only to ONE, but then allowing a commandline flag specifically to install from a specific user; and also to allow more sources, because not everyone wants to use rubygems.org anymore - I am now using solely github.com, which is a bit annoying that rubygems.org forced me back into corporate-controlled ecosystem, but at the least Microsoft does not usually disallow me from deleting my own code, whereas rubygems.org hijacks gems with that new corporate policy in place.)

**Comment by mperham** [comment]
Flori has never been responsive. I think it's reasonable to fork this repo to ruby/json and move forward, with or without him.

**Comment by hsbt** [comment]
I don't want to fork like `ruby/json`.

**Comment by flori** [comment]
I have looked into it again now, and I don't have the necessary permissions to transfer the ownership:

![Screenshot 2024-10-05 at 22 46 36](https://github.com/user-attachments/assets/9993d185-4658-41cc-829f-6959f17bb97b)

If you can give them to me, I could try again.

**Comment by byroot** [comment]
Thank you so much @flori, I'll see with @hsbt

**Comment by hsbt** [comment]
@flori Thank you for your action. I invite you as owner of ruby organization temporary. Could you try it again after accepting that invitation?

**Comment by flori** [comment]
This time it worked, I didn't know which team(s) to pick for access, so I picked "No Teams".

**Comment by hsbt** [comment]
Confirmed. I appreciate that. I will arrange "No Teams" later.

**Comment by byroot** [comment]
@flori thank you so much for arranging this.
