### ISSUE TITLE
Wishlist: Colorization

### ISSUE THREAD

**Issue by akimd** [ruby/json#722]
Hi,

In our project, it is quite frequent to have to look at JSON files, and in that case, colorization is helpful.  But AFAICT, there are no existing hooks that would allow to specify what to do with object keys for instance, or strings, etc.  As a workaround we often use `jq .`, but it's unfortunate to have to shell-out, since all the process is in Ruby.

Hooks would be a solution, but for ANSI colorization, pairs of pre/post strings would also suffice.

Cheers.

**Comment by byroot** [comment]
I think this is way too niche of an use case to justify the added complexity (especially since the generator has 3 implementations).

If I were you I'd just vendor the Ruby version of the generator and modify it slightly to do what you want: https://github.com/ruby/json/blob/f745ec145ef88f3dfe866001526a1270e49a2e89/lib/json/truffle_ruby/generator.rb

**Comment by akimd** [comment]
Thanks for your answer!
